"""Assemble the matched-completion deliverables in results/matched_completion/:

  dataset_manifest.json          (copied from the data directory)
  pair_generation_report.json    (copied from the pairs directory)
  training_results.csv           (already appended by the trainers)
  training_history.csv           (merged per-epoch histories)
  pair_results.csv               (already appended by eval_pairs)
  pair_predictions.parquet       (merged per-artifact predictions)
  table_matched_completion.tex
  figure_standard_vs_completion.pdf
  figure_learning_dynamics.pdf
  figure_margin_distributions.pdf

Idempotent: run at any time; missing runs are reported, not invented.
Run in the venv that has matplotlib + pyarrow (kip-venv).

    DATA_DIR=/root/LLMSeq/data python -m src.oc_completion.report_outputs
"""
from __future__ import annotations

import json
import shutil
from pathlib import Path

import numpy as np
import pandas as pd

from src.oc_completion.train_dl import CKPT_ROOT, DATA_ROOT, RESULTS_DIR

# validated categorical palette (fixed order, CVD-checked)
PALETTE = ["#2a78d6", "#eb6834", "#1baf7a", "#eda100", "#e87ba4",
           "#008300", "#4a3aa7", "#e34948"]
MODEL_ORDER = ["LSTM", "Transformer", "RNNTransformer", "bert_lora",
               "llama_lora", "llama_full", "lag_pair", "pos_lag_pair",
               "lag_trigram", "all_offset_pair", "all_offset_pair_xgb",
               "count26", "oracle"]
MODEL_LABEL = {
    "LSTM": "LSTM", "Transformer": "Transformer",
    "RNNTransformer": "RNNTransformer", "bert_lora": "BERT-base (LoRA)",
    "llama_lora": "Llama-3.2-1B (LoRA)", "llama_full": "Llama-3.2-1B (full FT)",
    "count26": "Letter-count LR", "lag_pair": "Lag-7 pair LR",
    "all_offset_pair": "All-offset pair LR",
    "all_offset_pair_xgb": "All-offset pair XGBoost",
    "pos_lag_pair": "Position-aware lag-pair LR",
    "lag_trigram": "Lag-7 trigram LR", "lag_trigram_key": "Key lag-trigram LR",
    "kgram1": "1-gram", "kgram2": "2-gram", "kgram3": "3-gram",
    "oracle": "Oracle (Y*)",
}
TASK_LABEL = {"ocdet": "OC-Deterministic", "ocnoisy": "OC-Noisy"}


def load_results():
    tr = pd.read_csv(RESULTS_DIR / "training_results.csv")
    tr = tr[tr["smoke"].astype(str).str.lower() != "true"]
    pr = pd.read_csv(RESULTS_DIR / "pair_results.csv")
    # latest row wins for duplicated (model, task, seed, family, background, split)
    pr = pr.drop_duplicates(
        subset=["model", "task", "seed", "family", "background", "split"],
        keep="last")
    tr = tr.drop_duplicates(subset=["model", "task", "seed"], keep="last")
    return tr, pr


def merge_histories() -> pd.DataFrame:
    rows = []
    for hist in CKPT_ROOT.rglob("history.json"):
        run = hist.parent
        if run.name.endswith("_smoke"):
            continue
        parts = run.relative_to(CKPT_ROOT).parts  # task_dir/model/seed_x
        task = {"oc_deterministic": "ocdet", "oc_noisy": "ocnoisy"}[parts[0]]
        with open(hist) as f:
            for rec in json.load(f):
                rows.append({"task": task, "model": parts[1],
                             "seed": parts[2].replace("seed_", ""), **rec})
    return pd.DataFrame(rows)


def merge_predictions(out: Path) -> None:
    pred_dir = RESULTS_DIR / "pair_predictions"
    frames = []
    for p in sorted(pred_dir.glob("*.parquet")):
        if "_smoke" in p.name:
            continue
        frames.append(pd.read_parquet(p))
    for p in sorted(pred_dir.glob("*.csv.gz")):
        if "_smoke" in p.name:
            continue
        frames.append(pd.read_csv(p))
    if frames:
        pd.concat(frames, ignore_index=True).to_parquet(out, index=False)


def agg_seeds(df: pd.DataFrame, value: str) -> pd.DataFrame:
    g = df.groupby(["task", "model"])[value].agg(["mean", "std", "count"])
    return g.reset_index()


def fmt(mean, std, count) -> str:
    if count > 1 and not np.isnan(std):
        return f"{mean:.3f}\\,$\\pm$\\,{std:.3f}"
    return f"{mean:.3f}"


def build_table(tr: pd.DataFrame, pr: pd.DataFrame, path: Path) -> None:
    two = pr[(pr["family"] == "two_hole") & (pr["background"] == "heldout")
             & (pr["split"] == "test")]
    one = pr[(pr["family"] == "one_hole") & (pr["background"] == "heldout")
             & (pr["split"] == "test")]
    lines = [
        "% Auto-generated by src.oc_completion.report_outputs",
        "\\begin{table*}[t]",
        "\\centering",
        "\\caption{Matched-completion analysis. Standard metrics on the "
        "original held-out test split; pair metrics on the held-out-background "
        "completion test pairs (10\\,000 matched two-hole pairs; margins on "
        "classification log-odds, tolerance $10^{-8}$). Mean\\,$\\pm$\\,sd "
        "over model seeds 9550--9552 where available.}",
        "\\label{tab:matched_completion}",
        "\\small",
        "\\begin{tabular}{llcccccc}",
        "\\toprule",
        "Model & Mode & AUC$_{Y}$ & AUC$_{Y^*}$ & One-hole acc & "
        "Matched acc & Tie rate & Mean margin \\\\",
    ]
    for task in ("ocdet", "ocnoisy"):
        lines.append("\\midrule")
        lines.append(f"\\multicolumn{{8}}{{l}}{{\\textbf{{{TASK_LABEL[task]}}}}}\\\\")
        seen = [m for m in MODEL_ORDER
                if m in set(tr[tr.task == task].model) | set(two[two.task == task].model)]
        for model in seen:
            trm = tr[(tr.task == task) & (tr.model == model)]
            twm = two[(two.task == task) & (two.model == model)]
            onm = one[(one.task == task) & (one.model == model)]
            mode = (trm["training_mode"].iloc[0] if len(trm)
                    else (twm["training_mode"].iloc[0] if len(twm) else ""))

            def cell(df, col):
                if not len(df) or col not in df:
                    return "--"
                v = df[col].astype(float)
                return fmt(v.mean(), v.std(), len(v))

            lines.append(" & ".join([
                MODEL_LABEL.get(model, model), str(mode),
                cell(trm, "test_auc_obs"), cell(trm, "test_auc_latent"),
                cell(onm, "pair_accuracy"), cell(twm, "pair_accuracy"),
                cell(twm, "tie_rate"), cell(twm, "mean_margin"),
            ]) + " \\\\")
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table*}", ""]
    path.write_text("\n".join(lines))


def build_figures(tr, pr, hist, out_dir: Path) -> None:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    plt.rcParams.update({
        "figure.dpi": 150, "font.size": 9, "axes.spines.top": False,
        "axes.spines.right": False, "axes.grid": True,
        "grid.color": "#e6e6e3", "grid.linewidth": 0.6,
        "axes.edgecolor": "#8a8a86", "axes.labelcolor": "#1a1a19",
        "text.color": "#1a1a19", "xtick.color": "#5f5f5c",
        "ytick.color": "#5f5f5c",
    })
    colors = {m: PALETTE[i % len(PALETTE)]
              for i, m in enumerate(["LSTM", "Transformer", "RNNTransformer",
                                     "bert_lora", "llama_lora", "llama_full"])}

    # ---- standard vs completion --------------------------------------
    two = pr[(pr["family"] == "two_hole") & (pr["background"] == "heldout")
             & (pr["split"] == "test")]
    fig, axes = plt.subplots(1, 2, figsize=(8.2, 3.6), sharey=True)
    for ax, task in zip(axes, ("ocdet", "ocnoisy")):
        merged = two[two.task == task].merge(
            tr[tr.task == task][["model", "seed", "test_auc_obs"]],
            on=["model", "seed"], how="left")
        neural = merged[merged.model.isin(colors)]
        basel = merged[~merged.model.isin(colors)]
        for _, r in basel.iterrows():
            if pd.isna(r["test_auc_obs"]):
                continue
            ax.scatter(r["test_auc_obs"], r["pair_accuracy"], s=26,
                       marker="s", color="#8a8a86", zorder=3)
            ax.annotate(MODEL_LABEL.get(r["model"], r["model"]),
                        (r["test_auc_obs"], r["pair_accuracy"]),
                        textcoords="offset points", xytext=(4, 4), fontsize=6.5,
                        color="#5f5f5c")
        for model, grp in neural.groupby("model"):
            ax.scatter(grp["test_auc_obs"], grp["pair_accuracy"], s=34,
                       color=colors[model], zorder=4,
                       label=MODEL_LABEL[model])
        ax.axhline(0.5, color="#8a8a86", lw=1, ls=":")
        if task == "ocnoisy":
            ax.axvline(0.670, color="#8a8a86", lw=1, ls="--")
            ax.text(0.671, 0.06, "AUC$^*$=0.670", rotation=90, fontsize=6.5,
                    color="#5f5f5c")
        ax.set_title(TASK_LABEL[task])
        ax.set_xlabel("Standard test AUC (observed labels)")
        ax.set_ylim(-0.02, 1.02)
    axes[0].set_ylabel("Matched pair accuracy (held-out bg)")
    handles, labels = axes[0].get_legend_handles_labels()
    if handles:
        fig.legend(handles, labels, loc="lower center", ncol=min(6, len(handles)),
                   frameon=False, fontsize=7, bbox_to_anchor=(0.5, -0.04))
    fig.tight_layout()
    fig.savefig(out_dir / "figure_standard_vs_completion.pdf",
                bbox_inches="tight")
    plt.close(fig)

    # ---- learning dynamics -------------------------------------------
    fig, axes = plt.subplots(1, 2, figsize=(8.2, 3.4), sharey=True)
    for ax, task in zip(axes, ("ocdet", "ocnoisy")):
        h = hist[(hist.task == task) & (hist.seed == "9550")]
        for model_dir, grp in h.groupby("model"):
            name = {"lstm": "LSTM", "transformer": "Transformer",
                    "rnntransformer": "RNNTransformer"}.get(model_dir, model_dir)
            c = colors.get(name, "#8a8a86")
            grp = grp.sort_values("epoch")
            ax.plot(grp["epoch"], grp["val_auc"], color=c, lw=1.6,
                    label=f"{MODEL_LABEL.get(name, name)}")
            ax.plot(grp["epoch"], grp["completion_pair_acc"], color=c, lw=1.6,
                    ls="--")
        ax.set_title(TASK_LABEL[task])
        ax.set_xlabel("Epoch")
        ax.set_ylim(0.35, 1.02)
    axes[0].set_ylabel("Validation AUC (solid) /\ncompletion pair acc. (dashed)")
    handles, labels = axes[0].get_legend_handles_labels()
    if handles:
        fig.legend(handles, labels, loc="lower center",
                   ncol=min(6, len(handles)), frameon=False, fontsize=7,
                   bbox_to_anchor=(0.5, -0.04))
    fig.tight_layout()
    fig.savefig(out_dir / "figure_learning_dynamics.pdf", bbox_inches="tight")
    plt.close(fig)

    # ---- margin distributions ----------------------------------------
    pred_path = RESULTS_DIR / "pair_predictions.parquet"
    if pred_path.exists():
        preds = pd.read_parquet(pred_path)
        sel = preds[(preds.family == "two_hole") & (preds.background == "heldout")
                    & (preds.split == "test")
                    & (preds.model.isin(colors))]
        if len(sel):
            models = [m for m in colors if m in set(sel.model)]
            fig, axes = plt.subplots(1, 2, figsize=(8.2, 3.4), sharey=False)
            for ax, task in zip(axes, ("ocdet", "ocnoisy")):
                data, names, cols = [], [], []
                for m in models:
                    g = sel[(sel.task == task) & (sel.model == m)
                            & (sel.seed.astype(str) == "9550")]
                    if len(g):
                        data.append(g["margin"].values)
                        names.append(MODEL_LABEL[m])
                        cols.append(colors[m])
                if not data:
                    continue
                parts = ax.violinplot(data, showmedians=True, widths=0.8)
                for body, c in zip(parts["bodies"], cols):
                    body.set_facecolor(c)
                    body.set_alpha(0.7)
                for key in ("cmedians", "cbars", "cmins", "cmaxes"):
                    parts[key].set_color("#5f5f5c")
                    parts[key].set_linewidth(1)
                ax.axhline(0, color="#8a8a86", lw=1, ls=":")
                ax.set_xticks(range(1, len(names) + 1))
                ax.set_xticklabels(names, rotation=20, ha="right", fontsize=7)
                ax.set_title(TASK_LABEL[task])
            axes[0].set_ylabel("Pair margin (log-odds), held-out bg")
            fig.tight_layout()
            fig.savefig(out_dir / "figure_margin_distributions.pdf",
                        bbox_inches="tight")
            plt.close(fig)


def main() -> None:
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    shutil.copy(DATA_ROOT / "dataset_manifest.json",
                RESULTS_DIR / "dataset_manifest.json")
    shutil.copy(DATA_ROOT / "pairs" / "pair_generation_report.json",
                RESULTS_DIR / "pair_generation_report.json")

    tr, pr = load_results()
    hist = merge_histories()
    hist.to_csv(RESULTS_DIR / "training_history.csv", index=False)
    merge_predictions(RESULTS_DIR / "pair_predictions.parquet")
    build_table(tr, pr, RESULTS_DIR / "table_matched_completion.tex")
    build_figures(tr, pr, hist, RESULTS_DIR)
    print(f"[report] outputs written to {RESULTS_DIR}")
    print(f"[report] training rows: {len(tr)}; pair rows: {len(pr)}; "
          f"history rows: {len(hist)}")


if __name__ == "__main__":
    main()
